sudo: required
services:
  - docker

before_install:
  - docker build -t mandarteli/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true mandarteli/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontendApp"
  env: "FrontendApp-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-441778933962"
  bucket_path: "frontendApp"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_kay: $AWS_PASS_KEY
  on:
    branch: main
